### ISSUE TITLE
Cant build full source thanks you +star

### ISSUE THREAD

**Issue by blitzcheat** [Shmurkio/EFI-SMBIOS-Spoofer#1]

**Comment by Shmurkio** [comment]
What error(s) are you getting? Compilation requires the [EDK2 LibC port](https://github.com/tianocore/edk2-libc).

**Comment by blitzcheat** [comment]
> What error(s) are you getting? Compilation requires the [EDK2 LibC port](https://github.com/tianocore/edk2-libc).

i just i dont know how to compile efi with visual studio I have never worked with efi ^^' I've been banned from Apex for 2 months already and it would be great to share the full build <3
Thank you very much for this beautiful project

**Comment by Shmurkio** [comment]
I uploaded the compiled .efi already: [Release](https://github.com/Shmurkio/EFI-SMBIOS-Spoofer/releases/tag/1.0). Is that what you were looking for?

**Comment by blitzcheat** [comment]
> I uploaded the compiled .efi already: [Release](https://github.com/Shmurkio/EFI-SMBIOS-Spoofer/releases/tag/1.0). Is that what you were looking for?

bootx64.efi i think because when i go in bios load efi nothing happen

**Comment by Shmurkio** [comment]
Set up a regular bootable USB to UEFI Shell and put Spoofer.efi in the root directory of the USB.

**Comment by blitzcheat** [comment]
i got working but my hwid not change =(
its for windows or VM ? ^^'

**Comment by Shmurkio** [comment]
What do you mean your HWID didn't change? Did you get the "Success" message from the spoofer? The spoofer works for regular hardware too, not only VM.

**Comment by blitzcheat** [comment]
> What do you mean your HWID didn't change? Did you get the "Success" message from the spoofer? The spoofer works for regular hardware too, not only VM.

yes i show message with ur github .

**Comment by Shmurkio** [comment]
I don't know. you must be doing a
something wrong then. You can't restart or you won't see the changes in Wondows.
